# Generated by Django 4.2.6 on 2024-10-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniproj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='owner',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='createdOn',
            new_name='joinedon',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='name',
        ),
    ]
